// Mocks generated by Mockito 5.4.6 from annotations
// in outty/test/screens/chat_screen_interaction_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:outty/models/match_model.dart' as _i9;
import 'package:outty/models/message_model.dart' as _i7;
import 'package:outty/models/user_model.dart' as _i4;
import 'package:outty/providers/auth_provider.dart' as _i2;
import 'package:outty/providers/chat_provider.dart' as _i6;
import 'package:outty/providers/match_provider.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i2.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> tryRestoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#tryRestoreSession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> register({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #password: password,
              #name: name,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> login({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> updateCurrentUser(_i4.UserModel? updated) =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrentUser, [updated]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> uploadProfilePhoto() =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteProfilePhotosForUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfilePhotosForUser, [uid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ChatProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatProvider extends _i1.Mock implements _i6.ChatProvider {
  MockChatProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  List<_i7.MessageModel> getMessages(String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [matchId]),
            returnValue: <_i7.MessageModel>[],
          )
          as List<_i7.MessageModel>);

  @override
  void listenToMessages(String? matchId) => super.noSuchMethod(
    Invocation.method(#listenToMessages, [matchId]),
    returnValueForMissingStub: null,
  );

  @override
  void stopListening(String? matchId) => super.noSuchMethod(
    Invocation.method(#stopListening, [matchId]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> sendMessage({
    required String? matchId,
    required String? senderId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #matchId: matchId,
              #senderId: senderId,
              #content: content,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> seedMatchMessage({
    required String? matchId,
    required String? fromUserId,
    required String? fromUserName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#seedMatchMessage, [], {
              #matchId: matchId,
              #fromUserId: fromUserId,
              #fromUserName: fromUserName,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markRead(String? matchId, String? currentUserId) =>
      (super.noSuchMethod(
            Invocation.method(#markRead, [matchId, currentUserId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MatchProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchProvider extends _i1.Mock implements _i8.MatchProvider {
  MockMatchProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.MatchModel> get matches =>
      (super.noSuchMethod(
            Invocation.getter(#matches),
            returnValue: <_i9.MatchModel>[],
          )
          as List<_i9.MatchModel>);

  @override
  List<_i4.UserModel> get feed =>
      (super.noSuchMethod(
            Invocation.getter(#feed),
            returnValue: <_i4.UserModel>[],
          )
          as List<_i4.UserModel>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get feedExhausted =>
      (super.noSuchMethod(Invocation.getter(#feedExhausted), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> load(_i4.UserModel? currentUser) =>
      (super.noSuchMethod(
            Invocation.method(#load, [currentUser]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i9.MatchModel?> swipeRight(
    _i4.UserModel? currentUser,
    _i4.UserModel? candidate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#swipeRight, [currentUser, candidate]),
            returnValue: _i3.Future<_i9.MatchModel?>.value(),
          )
          as _i3.Future<_i9.MatchModel?>);

  @override
  _i3.Future<void> swipeLeft(String? currentUserId, String? candidateId) =>
      (super.noSuchMethod(
            Invocation.method(#swipeLeft, [currentUserId, candidateId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.UserModel?> getUserById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [id]),
            returnValue: _i3.Future<_i4.UserModel?>.value(),
          )
          as _i3.Future<_i4.UserModel?>);

  @override
  void updateLastMessage(String? matchId, String? message) =>
      super.noSuchMethod(
        Invocation.method(#updateLastMessage, [matchId, message]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> markAsRead(String? matchId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [matchId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetFeed(_i4.UserModel? currentUser) =>
      (super.noSuchMethod(
            Invocation.method(#resetFeed, [currentUser]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
