// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIv2IPkgLyX6z8grUG94bB_SUMaRsTeQA',
    appId: '1:48519164027:web:1884a9f5358e29539732de',
    messagingSenderId: '48519164027',
    projectId: 'outty-firebase-backend',
    authDomain: 'outty-firebase-backend.firebaseapp.com',
    storageBucket: 'outty-firebase-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0UBjzlmuFLqUB1kpNx84W0vKj1620i4A',
    appId: '1:48519164027:android:974d1ad6457d40079732de',
    messagingSenderId: '48519164027',
    projectId: 'outty-firebase-backend',
    storageBucket: 'outty-firebase-backend.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4OpuISIN3sthHd012ZMoPNGWiMLBZka0',
    appId: '1:48519164027:ios:d932d09599caac499732de',
    messagingSenderId: '48519164027',
    projectId: 'outty-firebase-backend',
    storageBucket: 'outty-firebase-backend.firebasestorage.app',
    iosBundleId: 'com.example.outty',
  );
}
